### ISSUE TITLE
Does not process url of @fontface

### ISSUE THREAD

**Issue by francoisromain** [eirslett/storybook-builder-vite#247]
Hello 

I use this builder on a svelte project. Everything works fine locally with `start-storybook`. 
Then I deploy the storybook to github pages, which is in a subfolder: `https://my-name.github.io/my-project/`. 

To work with the `my-project` subfolder, I configured vite from `.storybook/main.cjs` like so : 

```
  async viteFinal(config, { configType }) {
    config.base = process.env.BASE_URL || config.base;

    return config;
  }
```
Then, in github actions, I do `BASE_URL=/my-project/ npm run build-storybook` and the storybook shows up on github pages. 

Everything works fine, except the webfonts. 

In the css file, webfont files are declared in `@font-face` like so : `src: url("/fonts/my-font.woff2") format("woff2")`. 
On build, this url is not processed to include the `BASE_URL`, so the webfont are not found on github pages at `/fonts/my-font.woff2` (should be `/my-project//fonts/my-font.woff2`).

Is it a bug, or is there something I should configure? 

Thank you

**Comment by eirslett** [comment]
I think that's somethink with Vite that you should configure. Not sure.

**Comment by drwpow** [comment]
I’d expect Vite to _not_ process your font URLs so they would be preserved as-written.

If you needed to grab that base URL from `process.env` you could dynamically inject your `@font-face`s in the template in `main.js` like so: https://storybook.js.org/docs/react/addons/writing-presets#previewmanager-templates

**Comment by francoisromain** [comment]
@drwpow your solution works. thank you very much. 

The small problem is I have to change my app to import the fonts from a separate file, 
so I can load them like this from stroybook (see [this commit](https://github.com/betagouv/dora-front/commit/61eee07f730f965bfcba21e77b6d93873279e81c)). 
This looks hacky. 

Why Vite should not process the font Urls? Is it different from other resources urls which are processed by Vite?

**Comment by drwpow** [comment]
> Why Vite should not process the font Urls?

It’s important to recognize that **`url()` in CSS isn’t a static import!** It’s actually an async import, and is capable of powerful flexibility. As such, processing `url()` in CSS is controversial and there’s no best practice that works for everyone. Just because you expect it to be transformed a certain way may not mean others have that expectation. Some people carefully architect those in a way that CSS only loads things when needed (i.e. inside `@media queries`), while others may expect `url()` to flatten all CSS into one file. There’s not really a way to make everyone happy.

In order to transform your CSS, you’ll need to use PostCSS or Sass and be explicit about what parts of your CSS you do/don’t want transformed, again, because there is no best solution here; only tradeoffs.

**Comment by francoisromain** [comment]
@drwpow Ok thank you for the very clear explanation. 

One last question: do you know an existing postcss plugin to process urls the way I want?

**Comment by drwpow** [comment]
Possibly [postcss-url](https://github.com/postcss/postcss-url)?

**Comment by IanVS** [comment]
Closing since this isn't a problem with the storybook vite builder.  Thanks for the help, @drwpow!
