### ISSUE TITLE
React HMR stuck in reload loop

### ISSUE THREAD

**Issue by amogower** [eirslett/storybook-builder-vite#65]
Thanks for all the great work on this builder so far - really excited to get this implemented into our projects.

I installed the latest version after seeing that [React HMR was fixed](https://github.com/eirslett/storybook-builder-vite/pull/53)

Starts up properly but then gets trapped in a reload loop with the following output:

<img width="804" alt="Screenshot 2021-07-07 at 15 48 14" src="https://user-images.githubusercontent.com/5639658/124781754-92916a00-df3b-11eb-8736-92ae12406b5f.png">

Followed by this output in the browser with Storybook showing a spinner in the component window:

<img width="391" alt="Screenshot 2021-07-07 at 15 51 40" src="https://user-images.githubusercontent.com/5639658/124781926-b654b000-df3b-11eb-92f5-fb05eb671f37.png">

Not sure if anyone else has experience this?  Any ideas on what's going on here?

Thanks in advance!

**Comment by IanVS** [comment]
I've found that it helps to specify a list of `entries` in my `optimizeDeps` config.  So my `viteFinal` looks something like this:

```
async viteFinal(config) {
    return {
      ...config,
      optimizeDeps: {
        ...config.optimizeDeps,
        // Entries are specified relative to the root
        entries: [`${path.relative(config.root, path.resolve(__dirname, '../src'))}/**/*.stories.tsx`],
        // Extra dependencies that aren't resolved through entries
        include: [...config.optimizeDeps.include, 'storybook-dark-mode'],
      },
    };
  },
```

As for the `global` error, it looks like one of the packages you are using is made to run in node, or relies on being polyfilled.  If you still get that error after updating your viteFinal, you will need to either polyfill `global` or try `window.global = window;`, probably in your `.storybook/preview.tsx` file.

**Comment by amogower** [comment]
Thanks @IanVS 

I will experiment with your suggestions tomorrow and let you know how I get on!

**Comment by amogower** [comment]
@IanVS based on your suggestions, I was able to fix the global issue but we are still experiencing the looping reloading...  This isn't a problem for earlier versions of `storybook-builder-vite` - is it related to changes made for HMR?

**Comment by IanVS** [comment]
I don't see any HRM loop in what you've posted so far.  Your first screenshot is what happens when vite isn't able to pre-bundle all of your dependencies in one go.  It hits one that it doesn't know about, bundles it, and restarts, then hits another.  That long process should only happen once, unless you're clearing the vite cache every time you start up storybook.  If you let that finish, kill storybook, and start it again, do you see the same messages?  Also, can you share your `viteFinal` config?

**Comment by eirslett** [comment]
This is how Vite works - it's lazy, so it doesn't optimize a dependency until it discovers it - when you browse in your application. Then it optimized the deps and triggers a browser reload. (And then it discovers another dependency, reload - and then another dependency, and so on). The refreshing goes on until all dependencies have been optimized.

If you add all these dependencies to optimizeDeps, it will happen when you start Vite instead of lazily. That should improve your startup experience.
